package seepick.localsportsclub.view.remark

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import io.github.oshai.kotlinlogging.KotlinLogging
import seepick.localsportsclub.persistence.ActivityRemarkDbo
import seepick.localsportsclub.persistence.ActivityRemarkDboRating
import seepick.localsportsclub.persistence.ActivityRemarkRepo
import seepick.localsportsclub.persistence.TeacherRemarkDbo
import seepick.localsportsclub.persistence.TeacherRemarkDboRating
import seepick.localsportsclub.persistence.TeacherRemarkRepo
import seepick.localsportsclub.service.model.ActivityRemark
import seepick.localsportsclub.service.model.ActivityRemarkRating
import seepick.localsportsclub.service.model.Remark
import seepick.localsportsclub.service.model.TeacherRemark
import seepick.localsportsclub.service.model.TeacherRemarkRating
import seepick.localsportsclub.service.model.Venue
import seepick.localsportsclub.service.model.toActivityRemark
import seepick.localsportsclub.service.model.toTeacherRemark
import seepick.localsportsclub.view.common.CustomDialog
import seepick.localsportsclub.view.shared.SharedModel

class RemarkViewModel(
    private val sharedModel: SharedModel,
    private val activityRepo: ActivityRemarkRepo,
    private val teacherRepo: TeacherRemarkRepo,
) : ViewModel() {

    private val log = KotlinLogging.logger {}
    var currentVenue by mutableStateOf<Venue?>(null)
    var currentIsForActivity by mutableStateOf(false)
    var remarks = mutableStateListOf<RemarkViewEntity>()

    fun showActivityRemarks(venue: Venue) {
        showDialog(venue, true)
    }

    fun showTeacherRemarks(venue: Venue) {
        showDialog(venue, false)
    }

    private fun showDialog(venue: Venue, isActivity: Boolean) {
        log.debug { "showDialog($venue, isActivity=$isActivity)" }
        currentVenue = venue
        currentIsForActivity = isActivity
        remarks.clear()
        remarks.addAll((if (isActivity) venue.activityRemarks else venue.teacherRemarks).map { it.toRemarkUiModel() }
            .sortedBy { it.name })

        sharedModel.customDialog.value = CustomDialog(
            title = "${if (isActivity) "Activity" else "Teacher"} Remarks",
            content = { RemarkView() },
            confirmLabel = "Save",
            showDismissButton = false,
            onConfirm = ::saveRemarks,
        )
    }

    private fun saveRemarks() {
        log.debug { "saveRemarks() $remarks" }
        val venueId = currentVenue!!.id
        if (currentIsForActivity) {
            val newDbos = activityRepo.reset(venueId, remarks.map { it.toActivityRemarkDbo() })
            currentVenue!!.activityRemarks.clear()
            currentVenue!!.activityRemarks.addAll(newDbos.map { it.toActivityRemark() })
        } else {
            val newDbos = teacherRepo.reset(venueId, remarks.map { it.toTeacherRemarkDbo() })
            currentVenue!!.teacherRemarks.clear()
            currentVenue!!.teacherRemarks.addAll(newDbos.map { it.toTeacherRemark() })
        }
    }

    fun addNewRemark() {
        remarks.add(
            0, RemarkViewEntity(
                id = -1,
                venueId = currentVenue!!.id,
                name = "",
                remark = "",
                rating = if (currentIsForActivity) RemarkRating.Activity(ActivityRemarkRating.Companion.default)
                else RemarkRating.Teacher(TeacherRemarkRating.Companion.default)
            )
        )
    }

    fun deleteRemark(remark: RemarkViewEntity) {
        val deleted = remarks.remove(remark)
        require(deleted) { "Remark $remark not found for deletion!" }
    }
}

private fun RemarkViewEntity.toActivityRemarkDbo() = ActivityRemarkDbo(
    id = -1, // will be auto-generated by DB
    venueId = this.venueId,
    name = this.name,
    remark = this.remark,
    rating = (this.rating as RemarkRating.Activity).rating.toActivityRemarkDboRating(),
)

private fun ActivityRemarkRating.toActivityRemarkDboRating() = when (this) {
    ActivityRemarkRating.Amazing -> ActivityRemarkDboRating.Amazing
    ActivityRemarkRating.Good -> ActivityRemarkDboRating.Good
    ActivityRemarkRating.Meh -> ActivityRemarkDboRating.Meh
    ActivityRemarkRating.Bad -> ActivityRemarkDboRating.Bad
}

private fun RemarkViewEntity.toTeacherRemarkDbo() = TeacherRemarkDbo(
    id = -1, // will be auto-generated by DB
    venueId = this.venueId,
    name = this.name,
    remark = this.remark,
    rating = (this.rating as RemarkRating.Teacher).rating.toTeacherRemarkDboRating(),
)

private fun TeacherRemarkRating.toTeacherRemarkDboRating() = when (this) {
    TeacherRemarkRating.Amazing -> TeacherRemarkDboRating.Amazing
    TeacherRemarkRating.Good -> TeacherRemarkDboRating.Good
    TeacherRemarkRating.Meh -> TeacherRemarkDboRating.Meh
    TeacherRemarkRating.Bad -> TeacherRemarkDboRating.Bad
}

private fun Remark.toRemarkUiModel() = RemarkViewEntity(
    id = id,
    venueId = venueId,
    name = name,
    remark = remark,
    rating = encapsulateRatingForUi(),
)

private fun Remark.encapsulateRatingForUi() = when (this) {
    is ActivityRemark -> RemarkRating.Activity(rating)
    is TeacherRemark -> RemarkRating.Teacher(rating)
    else -> error("Unhandled remark type: ${this::class.simpleName}")
}
