package seepick.localsportsclub.view.remark

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import io.github.oshai.kotlinlogging.KotlinLogging.logger
import seepick.localsportsclub.persistence.ActivityRemarkDbo
import seepick.localsportsclub.persistence.ActivityRemarkRepo
import seepick.localsportsclub.persistence.TeacherRemarkDbo
import seepick.localsportsclub.persistence.TeacherRemarkRepo
import seepick.localsportsclub.service.model.Venue
import seepick.localsportsclub.service.model.toRemarkDboRating
import seepick.localsportsclub.service.model.toRemarkViewEntity
import seepick.localsportsclub.view.common.CustomDialog
import seepick.localsportsclub.view.shared.SharedModel

class RemarkViewModel(
    private val sharedModel: SharedModel,
    private val activityRepo: ActivityRemarkRepo,
    private val teacherRepo: TeacherRemarkRepo,
) : ViewModel() {

    private val log = logger {}
    var currentVenue by mutableStateOf<Venue?>(null)
    var currentIsForActivity by mutableStateOf(false)
    val nameSuggestions = mutableStateListOf<String>()
    var remarks = mutableStateListOf<RemarkViewEntity>()

    fun showActivityRemarks(venue: Venue) {
        showDialog(venue, true)
    }

    fun showTeacherRemarks(venue: Venue) {
        showDialog(venue, false)
    }

    private fun showDialog(venue: Venue, isActivity: Boolean) {
        log.debug { "showDialog($venue, isActivity=$isActivity)" }
        currentVenue = venue
        currentIsForActivity = isActivity
        val realRemarks = if (isActivity) venue.activityRemarks else venue.teacherRemarks
        remarks.clear()
        remarks.addAll(realRemarks.sortedBy { it.name.value })

        nameSuggestions.clear()
        nameSuggestions.addAll(
            if (isActivity) venue.activities.map { it.name.trim(' ', '.', '_') }
                .filter { !it.endsWith("[OneFit]") }.distinct().sorted()
            else venue.activities.mapNotNull { it.teacher?.trim() }.distinct().sorted()
        )

        sharedModel.customDialog.value = CustomDialog(
            title = "${if (isActivity) "Activity" else "Teacher"} Remarks",
            content = {
                RemarkView(
                    height = it,
                    remarks = remarks,
                    nameSuggestions = nameSuggestions,
                    onAddNewClicked = ::addNewRemark,
                    onDelete = ::deleteRemark,
                )
            },
            confirmLabel = "Save",
            showDismissButton = false,
            onConfirm = ::saveRemarks,
        )
    }

    private fun saveRemarks() {
        log.debug { "saveRemarks() $remarks" }
        val venueId = currentVenue!!.id
        if (currentIsForActivity) {
            val newDbos = activityRepo.reset(venueId, remarks.map { it.toActivityRemarkDbo() })
            currentVenue!!.activityRemarks.clear()
            currentVenue!!.activityRemarks.addAll(newDbos.map { it.toRemarkViewEntity() })
        } else {
            val newDbos = teacherRepo.reset(venueId, remarks.map { it.toTeacherRemarkDbo() })
            currentVenue!!.teacherRemarks.clear()
            currentVenue!!.teacherRemarks.addAll(newDbos.map { it.toRemarkViewEntity() })
        }
    }

    fun addNewRemark() {
        log.debug { "addNewRemark()" }
        remarks.add(0, RemarkViewEntity.newPrototype(RemarkViewType.WithVenue(currentVenue!!.id)))
    }

    fun deleteRemark(remark: RemarkViewEntity) {
        val deleted = remarks.remove(remark)
        require(deleted) { "Remark $remark not found for deletion!" }
    }
}

private fun RemarkViewEntity.toActivityRemarkDbo() = ActivityRemarkDbo(
    id = -1, // will be auto-generated by DB
    venueId = (type as RemarkViewType.WithVenue).venueId,
    name = this.name.value,
    remark = this.remark,
    rating = this.rating.toRemarkDboRating(),
)

private fun RemarkViewEntity.toTeacherRemarkDbo() = TeacherRemarkDbo(
    id = -1, // will be auto-generated by DB
    venueId = (type as RemarkViewType.WithVenue).venueId,
    name = this.name.value,
    remark = this.remark,
    rating = this.rating.toRemarkDboRating(),
)
