name: Run Gradle on every push

on:
  push:
    branches:
      - main

jobs:
  gradle:
    runs-on: macos-latest #ubuntu-latest # TODO change back
    steps:
      # FIXME DELETE ME
      - run: echo "This job is now running on a ${{ runner.os }} server. Ref is ${{ github.ref }} and RefName ${{ github.ref_name }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew check
