name: Delme Win

on:
  push:
# file:///D:/a/LocalSportsClub/LocalSportsClub/build/reports/problems/problems-report.html
jobs:
  build-and-upload:
    runs-on: windows-latest
    name: Building and uploading compose artifact
    steps:
      - name: Dump info
        run: echo "This job is now running on a ${{ runner.os }} server. Ref is ${{ github.ref }} and RefName ${{ github.ref_name }} workspace ${{ github.workspace }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: List files in the repository
        run: dir ${{ github.workspace }}
      - name: Execute Gradle build
        run: gradlew.bat packageDistributionForCurrentOS -Plsc.version=1.0.0 -Plsc.gcalClientId=${{ secrets.GCAL_CLIENT_ID }} -Plsc.gcalClientSecret=${{ secrets.GCAL_CLIENT_SECRET }}
      - name: List files in the repository
        run: dir ${{ github.workspace }}\build
