name: Delme Win

on:
  push:

jobs:
  build-and-upload:
    runs-on: windows-latest
    name: Building and uploading compose artifact
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server. Ref is ${{ github.ref }} and RefName ${{ github.ref_name }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew packageDistributionForCurrentOS -Plsc.version=${{ github.ref_name }} -Plsc.gcalClientId=${{ secrets.GCAL_CLIENT_ID }} -Plsc.gcalClientSecret=${{ secrets.GCAL_CLIENT_SECRET }}
      - name: List files in the repository
        run: dir ${{ github.workspace }}/build
